MVCGarage/Models/Entities/Member.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace MVCGarage.Models.Entities
{
    [Index(nameof(PersonalIdentityNumber), IsUnique = true)]
    public class Member
    {
        public Member()
        {
            Vehicles = new List<Vehicle>();
        }
        public int Id { get; set; }
        [Required]
        public DateTime ProMembershipToDate { get; set; }
        [Required] 
        [StringLength(13)]
        //TODO make similar uniquecheck? [Remote(action: "CheckIfRegIsUnique", controller: "Vehicles")]
        public string? PersonalIdentityNumber { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; } = string.Empty;
        [Required]
        [StringLength(50)]
        public string LastName { get; set; } = string.Empty;
        public bool HasReceived2YearsProMembership { get; set; }

        //Nav prop
        public ICollection<Vehicle> Vehicles { get; set; }
    }
}

MVCGarage/Models/ViewModels/DetailsViewModel.cs
using Microsoft.EntityFrameworkCore;
using MVCGarage.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace MVCGarage.Models.ViewModels
{

    [Index(nameof(RegistrationNumber), IsUnique = true)]
    public class DetailsViewModel
    {
        public int Id { get; set; }
        [Required]
        public Color Color { get; set; }
        [Required]
        [Display(Name = "Type of Vehicle")]
        public string? VehicleTypeName { get; set; }
        [Required]
        [StringLength(40)]
        [Display(Name = "Registration Number")]
        public string? RegistrationNumber { get; set; }
        [Required]
        [StringLength(40)]
        public string? Brand { get; set; }
        [Required]
        [StringLength(40)]
        public string? Model { get; set; }
        [Range(0, int.MaxValue)]
        [Display(Name = "Number of Wheels")]
        public int WheelCount { get; set; }

        [Display(Name = "First Name")]
        public string OwnerFirstName { get; set; } = string.Empty;
        [Display(Name = "Last Name")]
        public string OwnerLastName { get; set; } = string.Empty;


        [Display(Name = "Arrival Time")]
        public DateTime? ArrivalTime { get; set; }
        [Display(Name = "Parked Time")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d\\d\\ hh\\h\\ mm\\m}")]
        public TimeSpan? ParkedTime { get; set; }
    }

}

MVCGarage/Models/ViewModels/Members/DetailsViewModel.cs
using Microsoft.EntityFrameworkCore;
using MVCGarage.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace MVCGarage.Models.ViewModels.Members
{
    public class DetailsViewModel
    {
        public DetailsViewModel()
        {
            Vehicles = new List<MemberVehicleModel>();
        }
        public int Id { get; set; }
        [Display(Name = "First Name")]
        public string? FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string? LastName { get; set; }
        public Membership.MembershipType Type { get; set; }
        public List<MemberVehicleModel> Vehicles { get; set; }
        public int? VehicleId { get; set; }

        public bool? ParkSuccess { get; set; }
        public string? ParkFailedReason { get; set; }
        public string? modalTitleText { get; set; }
        public string? modalBodyText { get; set; }
    }
}

MVCGarage/Models/ViewModels/Members/IndexMemberViewModel.cs
using MVCGarage.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace MVCGarage.Models.ViewModels.Members
{
    public class IndexMemberViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Nr Of Vehicles")]
        public int? NrOfVehicles { get; set; }
        [Display(Name = "First Name")]
        public string? FirstName { get; set; }
        [Display(Name = "Birth Date")]
        public string? BirthDate { get; set; }
        [Display(Name = "Last Name")]
        public string? LastName { get; set; }
    }
}

MVCGarage/Models/ViewModels/Members/ListViewModel.cs
using MVCGarage.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace MVCGarage.Models.ViewModels.Members
{
    public class ListViewModel
    {
        public IEnumerable<IndexMemberViewModel> MemberList { get; set; } = new List<IndexMemberViewModel>();
        [Display(Name = "Personal Identity Number")]
        public string? SearchPersonalIdentityNumber { get; set; }
        [Display(Name = "Name")]
        public string? SearchName { get; set; }
        [Display(Name = "Vehicle Registration Number")]
        public string? SearchRegistrationNumber { get; set; }
        public bool HasExpandedSearchItem { get; set; } = false;
    }
}

MVCGarage/Models/ViewModels/Members/MemberVehicleModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVCGarage.Models.ViewModels.Members
{
    public class MemberVehicleModel
    {
        public int Id { get; set; }
        [Display(Name = "Registration Number")]
        public string? RegistrationNumber { get; set; }
        public string? Brand { get; set; }
        public string? Model { get; set; }
        public bool IsParked { get; set; }
    }
}

MVCGarage/Models/ViewModels/Members/RegisterViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using MVCGarage.Validations;

namespace MVCGarage.Models.ViewModels.Members
{
#nullable disable
    [Index(nameof(PersonalIdentityNumber), IsUnique = true)]
    public class RegisterViewModel
	{
        public int Id { get; set; }

        [Required]
        [StringLength(13)]
		[Display(Name = "Personal Identity Number")]
        [Remote(action: "CheckIfPINIsUnique", controller: "Members")]
        [ValidatePersonalIdentityNumber(ErrorMessage = "Invalid Personal Identity Number")]
        public string PersonalIdentityNumber { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "First Name")]
        [ValidateFirstName(ErrorMessage = "First Name can't be the same as Last Name")]
        public string FirstName { get; set; } = string.Empty;

        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; } = string.Empty;

        public bool RegisterSuccess { get; set; } = false;

		//public string? Error { get; set; }
	}
}

MVCGarage/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using MVCGarage.Data;
using MVCGarage.Models.Entities;
using MVCGarage.Models.ViewModels;

namespace MVCGarage.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly MVCGarageContext _context;
        private readonly IOptions<PriceSettings> options;

        public VehiclesController(MVCGarageContext context, IOptions<PriceSettings> options)
        {
            _context = context;
            this.options = options;
        }

        public async Task<IActionResult> Index(ListViewModel lvm)
        {
            lvm.HasExpandedSearchItem =
                lvm.SearchType != null || lvm.SearchWheelCount != null ||
                !string.IsNullOrEmpty(lvm.SearchBrand) || !string.IsNullOrEmpty(lvm.SearchModel);

            var dbVehicles = await _context.Vehicle
                .AsNoTracking()
                .Include(v => v.Member)
                .Join(_context.VehicleAssignment!,
                v => v.Id,
                va => va.VehicleId,
                (v, va) => new { vehicle = v, asgnmt = va })
                .WhereIf(lvm.SearchRegistrationNumber != null, x => x.vehicle.RegistrationNumber != null && x.vehicle.RegistrationNumber.StartsWith(lvm.SearchRegistrationNumber!.Trim()))
                .WhereIf(lvm.SearchBrand != null, x => x.vehicle.Brand != null && x.vehicle.Brand.StartsWith(lvm.SearchBrand!.Trim()))
                .WhereIf(lvm.SearchWheelCount != null, x => x.vehicle.WheelCount == lvm.SearchWheelCount)
                .WhereIf(lvm.SearchModel != null, x => x.vehicle.Model != null && x.vehicle.Model.StartsWith(lvm.SearchModel!.Trim()))
                .WhereIf(lvm.SearchType != null, x => x.vehicle.VehicleType.Id == lvm.SearchType)
                .Select(v => new IndexVehicleViewModel()
                {
                    Id = v.vehicle.Id,
                    RegistrationNumber = v.vehicle.RegistrationNumber,
                    Type = new VehicleType()
                    {
                        Id = v.vehicle.VehicleType.Id,
                        Name = v.vehicle.VehicleType.Name,
                        NeededSize = v.vehicle.VehicleType.NeededSize
                    },
                    ArrivalTime = v.asgnmt.ArrivalDate,
                    ParkedTime = DateTime.Now.Subtract(v.asgnmt.ArrivalDate),
                    Owner = $"{v.vehicle.Member.FirstName} {v.vehicle.Member.LastName}",
                    MembershipType = new Membership(v.vehicle.Member.ProMembershipToDate).Type
                })
                .ToListAsync();

            var orderedVehicles =
                lvm.Order == Order.RegistrationNumber ? dbVehicles.OrderAscOrDesc(lvm.Desc, v => v.RegistrationNumber)
                : lvm.Order == Order.Type ? dbVehicles.OrderAscOrDesc(lvm.Desc, v => v.Type.Id)
                : lvm.Order == Order.ParkedTime ? dbVehicles.OrderAscOrDesc(lvm.Desc, v => v.ParkedTime)
                : dbVehicles.OrderAscOrDesc(lvm.Desc, v => v.ArrivalTime);

            lvm.VehicleList = orderedVehicles.GroupBy(x => x.Id).Select(y => y.First());

            lvm.VehicleTypes = await _context.VehicleType.AsNoTracking().ToListAsync();
            return View(lvm);
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .AsNoTracking()
                .Include(v => v.VehicleType)
                .Include(v => v.VehicleAssignments)
                .FirstOrDefaultAsync(v => v.Id == id);

            if (vehicle == null)
            {
                return NotFound();
            }

            var member = await _context.Member.AsNoTracking().FirstOrDefaultAsync(m => m.Id == vehicle.MemberId);

            var vehicleType = vehicle.VehicleType;

            if (member == null || vehicleType == null)
            {
                return NotFound();
            }

            var model = new DetailsViewModel
            {
                Brand = vehicle.Brand,
                Color = vehicle.Color,
                Id = vehicle.Id,
                Model = vehicle.Model,
                RegistrationNumber = vehicle.RegistrationNumber,
                VehicleTypeName = vehicleType.Name,
                WheelCount = vehicle.WheelCount,
                OwnerFirstName = member.FirstName,
                OwnerLastName = member.LastName
            };

            var va = vehicle.VehicleAssignments.FirstOrDefault();

            if (va != null)
            {
                model.ArrivalTime = va.ArrivalDate;
                model.ParkedTime = DateTime.Now.Subtract(va.ArrivalDate);
            };

            return View(model);
        }

        public async Task<List<VehicleType>> getVehicleTypesPlusCreate()
        {
            var dbVehicleTypes = await _context.VehicleType.AsNoTracking().ToListAsync();
            dbVehicleTypes.Add(new VehicleType()
            {
            Id = 0,
                Name = "Create New"
            });
            return dbVehicleTypes;
        }

        public async Task<IActionResult> Add(int? id)
        {
            if (id == null || !await _context.Member.AsNoTracking().AnyAsync(m => m.Id == id))
            {
                return NotFound();
            }
            var dbVehicleTypes = await getVehicleTypesPlusCreate();

            var avvm = new AddVehicleViewModel
            {
                MemberId = (int)id,
                VehicleTypes = dbVehicleTypes,
                VehicleTypeId = dbVehicleTypes.FirstOrDefault()?.Id ?? 0,
                VehicleTypeStartOpen = false
            };

            return View(avvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddVehicleViewModel avvm)
        {
            if (ModelState.IsValid)
            {
                if(avvm.VehicleTypeId == 0)
                { 
                    var vehicleType = new VehicleType
                    {
                        Name = avvm.VehicleTypeName!,
                        NeededSize = avvm.VehicleTypeNeededSize
                    };
                    _context.Vehicle.Add(new Vehicle
                    {
                        Brand = avvm.Brand,
                        Color = avvm.Color,
                        Model = avvm.Model,
                        RegistrationNumber = avvm.RegistrationNumber,
                        WheelCount = avvm.WheelCount,
                        MemberId = avvm.MemberId,
                        VehicleType = vehicleType
                    });
                }
                else
                {
                    _context.Vehicle.Add(new Vehicle
                    {
                        Brand = avvm.Brand,
                        Color = avvm.Color,
                        Model = avvm.Model,
                        RegistrationNumber = avvm.RegistrationNumber,
                        WheelCount = avvm.WheelCount,
                        MemberId = avvm.MemberId,
                        VehicleTypeId = avvm.VehicleTypeId
                    });
                }
                await _context.SaveChangesAsync();
                avvm.AddSuccess = true;
            }

            var dbVehicleTypes = await getVehicleTypesPlusCreate();
            avvm.VehicleTypes = dbVehicleTypes;

            if (avvm.VehicleTypeId == 0)
                avvm.VehicleTypeStartOpen = true;

            return View(avvm);
        }

        public string MinifyAndUpperCaseString(string stringToMinify)
        {
            return stringToMinify.Replace(" ", "").Replace("-", "");
        }

        public async Task<IActionResult> CheckIfRegIsUnique(string registrationNumber)
        {
            try
            {
                if (await _context.Vehicle.AsNoTracking().AnyAsync(v => v.RegistrationNumber == registrationNumber))
                    return Json("A vehicle with that registration number is already parked. Try modifying the vehicle instead.");
            }
            catch
            {                
            }
            //if database messed up on validation it is not a big deal if this was not validated (since it is not to be trusted once we reach backend), we validate once more on database index
            return Json(true);
        }

        // GET
        public async Task<IActionResult> Modify(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .AsNoTracking()
                .Include(v => v.VehicleType)
                .Include(v => v.Member)
                .FirstOrDefaultAsync(v => v.Id == id);

            if (vehicle == null)
            {
                return NotFound();
            }

            var viewModel = new ChangeViewModel()
            {
                Id = vehicle.Id,
                Brand = vehicle.Brand,
                Color = vehicle.Color,
                Model = vehicle.Model,
                RegistrationNumber = vehicle.RegistrationNumber,
                WheelCount = vehicle.WheelCount,
                VehicleTypeName = vehicle.VehicleType.Name,
                OwnerFirstName = vehicle.Member.FirstName,
                OwnerLastName = vehicle.Member.LastName
            };
            return View(viewModel);

        }

        // POST
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

MVCGarage/Views/Members/Details.cshtml
@model MVCGarage.Models.ViewModels.Members.DetailsViewModel

@{
    ViewData["Title"] = "Details";
}
<div class="m-2">
    <a asp-action="Index">Back to Members</a>
</div>
@if (@Model.ParkSuccess != null) {
    <!-- Button trigger modal -->
    <button type="button" id="clickable" class="btn btn-primary d-none" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        Launch static backdrop modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">@Model.modalTitleText</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        @Model.modalBodyText
      </div>
      <div class="modal-footer">
        <a asp-action="Index" class="btn btn-primary">To Members List</a>
      </div>
    </div>
  </div>
</div>
<script src="/js/clickable.js"></script>
}
<h2>Details</h2>
<hr />
<div>
    <h4>Member</h4>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div class="row">   
    <div class="col-lg-8 order-lg-first">
        <div class="container bg-light rounded shadow p-2">
            <h3>Member Vehicles</h3>
            <table class="table table-striped hoverable">
                <thead>
                    <tr>
                        <th>
                            @{ MVCGarage.Models.ViewModels.Members.MemberVehicleModel dummyModel = null!; }
                            @Html.DisplayNameFor(dummyParam => dummyModel.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(dummyParam => dummyModel.Model)
                        </th>
                        <th>
                            @Html.DisplayNameFor(dummyParam => dummyModel.RegistrationNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(dummyParam => dummyModel.Brand)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Vehicles) {
                    <tr class="clickableTR" myattribute="/Vehicles/Details/@item.Id">
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Model)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RegistrationNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Brand)
                        </td>
                        <td>
                            @if(item.IsParked) 
                            {
                                <a asp-controller="Vehicles" asp-action="Checkout" class="btn btn-danger form-control" asp-route-id="@item.Id">Checkout</a>
                            }
                            else 
                            {
                                <form asp-action="Details">
                                    <input type="hidden" asp-for="Id" />
                                    <input type="hidden"  asp-for="VehicleId" value="@item.Id" />
                                    <input type="submit" class="btn btn-success form-control" value="Park" />
                                </form>
                            }
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <a class="btn btn-primary" asp-controller="Vehicles" asp-action="Add" asp-route-id="@Model.Id">Add Vehicle</a>
        </div>
    </div>
</div>
<div>
    @*<a asp-action="Modify" asp-route-id="@Model?.Id" class="btn btn-dark">Modify</a>*@
</div>
                                    
@section Scripts {
 <script src="~/js/clickableRows.js"></script>
}

MVCGarage/Views/Members/Index.cshtml
@model MVCGarage.Models.ViewModels.Members.ListViewModel

@{
    ViewData["Title"] = "Members";
}


<h2>Members</h2>
<hr />
<p>
    <a asp-action="Register" class="btn btn-primary mt-2 mb-2" role="button">Register</a>
</p>
<div class="row">
    <div class="col-lg-4 order-lg-last mb-4">
        <div class="accordion bg-secondary bg-opacity-10 p-2 rounded shadow">
            <h3>Search</h3>
                <form asp-action="Index">
                <div class="form-floating">
                    <input type="text" asp-for="SearchPersonalIdentityNumber" class="form-control" name="SearchPersonalIdentityNumber" />
                    <label asp-for="SearchPersonalIdentityNumber" class="form-label"></label>
                </div>
                <div class="accordion-item p-0 mt-2 border-0">
                <h5 class="accordion-header">
                    <button class="accordion-button alert-primary @if(!Model.HasExpandedSearchItem) @Html.Raw("collapsed")" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="@Html.Raw(Model.HasExpandedSearchItem)" aria-controls="collapseOne">
                    More search options...
                    </button>
                </h5>
                <div id="collapseOne" class="accordion-collapse collapse @if(Model.HasExpandedSearchItem) @Html.Raw("show")" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body text-dark bg-primary bg-opacity-10">
                        <div class="form-floating">
                            <input type="text" asp-for="SearchName" class="form-control" name="searchName" />
                            <label asp-for="SearchName" class="form-label"></label>
                        </div>
                        <div class="form-floating">
                            <input type="text" asp-for="SearchRegistrationNumber" class="form-control" name="SearchRegistrationNumber" />
                            <label asp-for="SearchRegistrationNumber" class="form-label"></label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input type="submit" class="btn btn-dark mt-2 mb-2" value="Search"/>
                </div>
                <div class="col text-end">
                    <a href="/Members" class="btn btn-outline-dark mt-2 mb-2" role="button">Reset Search</a>
                </div>
            </div>
            </form>
        </div>
    </div>


    <div class="col-lg-8 order-lg-first">
        <div class="container bg-light rounded shadow p-2">
            <table class="table table-striped hoverable">
                <thead>
                    <tr>
                        <th>
                            @{ MVCGarage.Models.ViewModels.Members.IndexMemberViewModel dummyModel = null!; }
                            @Html.DisplayNameFor(dummyParam => dummyModel.BirthDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(dummyParam => dummyModel.FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(dummyParam => dummyModel.LastName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(dummyParam => dummyModel.NrOfVehicles)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.MemberList) {
                    <tr class="clickableTR" myattribute="/Members/Details/@item.Id">
                        <td>
                            @Html.DisplayFor(modelItem => item.BirthDate)
                        </td>                        
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NrOfVehicles)
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

@section Scripts {
 <script src="~/js/clickableRows.js"></script>
}

MVCGarage/Views/Members/Register.cshtml
@model MVCGarage.Models.ViewModels.Members.RegisterViewModel

@{
    ViewData["Title"] = "Register Member";
}

@if(@Model.RegisterSuccess) {
    <!-- Button trigger modal -->
    <button type="button" id="clickable" class="btn btn-primary d-none" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
      Launch static backdrop modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Registration successful!</h5>
@*            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>*@
          </div>
@*          <div class="modal-body">
            When you no longer want to stay parked. Choose Checkout in the Parked Vehicles List.
          </div>*@
          <div class="modal-footer">
            <a asp-action="Index" class="btn btn-primary">Return to Members</a>
          </div>
        </div>
      </div>
    </div>
    <script src="/js/clickable.js"></script>
}

<div class="m-2">
    <a asp-action="Index">Back to Members</a>
</div>
<h2>Register</h2>
<hr />
<div>
    <h4>Member</h4>
    <form asp-action="Register">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-floating">
            <input asp-for="PersonalIdentityNumber" class="form-control" />
            <span asp-validation-for="PersonalIdentityNumber" class="text-danger"></span>
            <label asp-for="PersonalIdentityNumber" class="form-label"></label>
        </div>
        <div class="form-floating">
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
            <label asp-for="FirstName" class="form-label"></label>
        </div>
        <div class="form-floating">
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
            <label asp-for="LastName" class="form-label"></label>
        </div>
        <div class="form-group mt-2">
            <input type="submit" value="Register" class="btn btn-primary" />
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}